import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Logo from "../svg/logo.svg";
import Facebbok from "../svg/icon-facebook.svg";
import Instagram from "../svg/icon-instagram.svg";
import Twitter from "../svg/icon-twitter.svg";
import Android from "../svg/icon-android.svg";
import Apple from "../svg/icon-apple.svg";
import Button from "../components/button";
export default function Home() {
    return (
        <div className={styles.main_container}>
            <Head>
                <title>Frontend Mentor | Equalizer landing page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/images/favicon-32x32.png" />
            </Head>
            <header className={styles.header}>
                <Logo />
            </header>
            <main className={styles.main}>
                <div className={styles.main_wrap}>
                    <h1> We make your music sound extraordinary.</h1>
                    <p>
                        A system audio equalizer specifically designed for
                        Android and iOS. Freely tune the way your music sounds
                        with a professional grade parametric EQ & volume mixer.
                        Control bass, mids, treble, gain control, reverb, and
                        more!
                    </p>
                </div>
            </main>

            <section className={styles.section_info} aria-label="more info">
                <div className={styles.info_container}>
                    <div className={styles.container_wrap}>
                        <div className={styles.info_image}>
                            <img src="/images/illustration-app.png" alt="" />
                        </div>

                        <div className={styles.info}>
                            <h2>Premium EQ</h2>
                            <p>
                                Get expert-level control with a robust
                                equalizer, volume mixer, and spatial audio. Take
                                your listening experience to a whole new level
                                and access all our incredible features!
                            </p>
                            <p>
                                <span>$4</span> / month
                            </p>
                            <div className={styles.btn_wrap}>
                                <Button
                                    color="dark"
                                    icon={<Apple />}
                                    title="iOS Download "
                                    colorBtn="darkBtn"
                                />
                                <Button
                                    color="light"
                                    icon={<Android />}
                                    title="Android Download "
                                    colorBtn="lightBtn"
                                />
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <footer className={styles.footer}>
                <div className={styles.footer_wrap}>
                    <div className={styles.wrap}>
                        <Logo />
                        <p>
                            All rights reserved © Equalizer 2021 <br />
                            Have any problems? Contact us via social media or
                            email us at <span>equalizer@example.com</span>
                        </p>
                    </div>

                    <div className={styles.social}>
                        <Facebbok /> <Instagram /> <Twitter />
                    </div>
                </div>
            </footer>
        </div>
    );
}
